name = "chatsvtr"
compatibility_date = "2024-07-16"
pages_build_output_dir = "."

# Enable Gzip/Brotli compression for all text-based assets
[[headers]]
for = "*.css"
[headers.values]
"Content-Encoding" = "gzip"
"Cache-Control" = "public, max-age=31536000, immutable"

[[headers]]
for = "*.js"
[headers.values]
"Content-Encoding" = "gzip"
"Cache-Control" = "public, max-age=31536000, immutable"

[[headers]]
for = "*.html"
[headers.values]
"Content-Encoding" = "gzip"
"Cache-Control" = "public, max-age=3600"

[[headers]]
for = "*.webp"
[headers.values]
"Cache-Control" = "public, max-age=31536000, immutable"

[[headers]]
for = "*.png"
[headers.values]
"Cache-Control" = "public, max-age=31536000, immutable"

[[headers]]
for = "*.jpg"
[headers.values]
"Cache-Control" = "public, max-age=31536000, immutable"

[[vectorize]]
binding = "SVTR_VECTORIZE"
index_name = "autorag-svtr-knowledge-base-ai"

[ai]
binding = "AI"

# AI Gateway配置 - 已创建并启用  
# 注意：AI Gateway通过env.AI绑定自动使用，无需额外配置

# KV存储绑定 - 扩展使用
[[kv_namespaces]]
binding = "SVTR_CACHE"
id = "6c8056d110964334af5e44e875fad54e"

[[kv_namespaces]]
binding = "SVTR_SESSIONS"
id = "070deb624f41469f9cf7d8dde603f8b9"

# OAuth 认证环境变量
[vars]
APP_URL = "https://auth.svtr.ai"
ALLOWED_RETURN_TO = "https://svtr.ai,https://svtrglobal.com,https://svtrai.com,http://localhost:3000"
GOOGLE_CLIENT_ID = "369633995349-7apl7m77mpeo4231b1kl2v3nonqi60ga.apps.googleusercontent.com"
GITHUB_CLIENT_ID = "Ov23liTtfl1NQmZtq2em"

# OAuth 密钥通过wrangler secrets设置
# wrangler secret put GOOGLE_CLIENT_SECRET
# wrangler secret put GITHUB_CLIENT_SECRET

[[headers]]
for = "*.avif"
[headers.values]
"Cache-Control" = "public, max-age=31536000, immutable"
"Content-Type" = "image/avif"