# Cloudflare Pages 配置文件
name = "chatsvtr"
compatibility_date = "2024-07-16"

[build]
command = "echo 'Static site, no build required'"
cwd = "."
watch_dir = "."

[build.upload]
format = "assets"
dir = "."
include = [
  "*.html",
  "assets/**/*",
  "pages/**/*",
  "favicon.ico"
]
exclude = [
  "*.md",
  "*.log",
  "*.sh",
  "scripts/**/*",
  "config/**/*",
  "node_modules/**/*",
  "banner-*.html",
  "preview-*.html",
  "test-*.html",
  "index-*.html",
  "server.log",
  "tatus"
]

# 页面设置
[pages]
# 启用SPA模式
routes = [
  { pattern = "/*", custom_headers = { "X-Frame-Options" = "DENY", "X-XSS-Protection" = "1; mode=block", "X-Content-Type-Options" = "nosniff" } }
]

# 静态资源缓存
[[pages.headers]]
for = "/assets/*"
[pages.headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[pages.headers]]
for = "*.html"
[pages.headers.values]
Cache-Control = "public, max-age=0, must-revalidate"

# 重定向规则
[[pages.redirects]]
from = "/AI 100.html"
to = "/pages/ai-100.html"
status = 301

[[pages.redirects]]
from = "/凯瑞.jpg"
to = "/assets/images/qr-code.jpg"
status = 301

# SPA fallback
[[pages.redirects]]
from = "/*"
to = "/index.html"
status = 200