name = "chatsvtr"
compatibility_date = "2024-07-16"

# Enable Gzip/Brotli compression for all text-based assets
[[headers]]
for = "*.css"
[headers.values]
"Content-Encoding" = "gzip"
"Cache-Control" = "public, max-age=31536000, immutable"

[[headers]]
for = "*.js"
[headers.values]
"Content-Encoding" = "gzip"
"Cache-Control" = "public, max-age=31536000, immutable"

[[headers]]
for = "*.html"
[headers.values]
"Content-Encoding" = "gzip"
"Cache-Control" = "public, max-age=3600"

[[headers]]
for = "*.webp"
[headers.values]
"Cache-Control" = "public, max-age=31536000, immutable"

[[headers]]
for = "*.png"
[headers.values]
"Cache-Control" = "public, max-age=31536000, immutable"

[[headers]]
for = "*.jpg"
[headers.values]
"Cache-Control" = "public, max-age=31536000, immutable"

[[vectorize]]
binding = "SVTR_VECTORIZE"
index_name = "svtr-knowledge-base"

[ai]
binding = "AI"