name = "chatsvtr"
compatibility_date = "2024-07-16"
pages_build_output_dir = "."

[[vectorize]]
binding = "SVTR_VECTORIZE"
index_name = "autorag-svtr-knowledge-base-ai"

[ai]
binding = "AI"

# AI Gateway配置 - 已创建并启用  
# 注意：AI Gateway通过env.AI绑定自动使用，无需额外配置

# KV存储绑定 - 扩展使用
[[kv_namespaces]]
binding = "SVTR_CACHE"
id = "6c8056d110964334af5e44e875fad54e"

[[kv_namespaces]]
binding = "SVTR_SESSIONS"
id = "070deb624f41469f9cf7d8dde603f8b9"

[[kv_namespaces]]
binding = "USER_BEHAVIOR_KV"
id = "c1d6ce9269ac40dea434e064a1d31204"
preview_id = "33c9f9a8b5994c6794318debe0094325"

# OAuth 认证环境变量 - 多域名支持
[vars]
APP_URL = "https://svtr.ai"
ALLOWED_RETURN_TO = "https://svtr.ai,https://svtrai.com,https://svtr.cn,https://svtrglobal.com,http://localhost:3000"
GOOGLE_CLIENT_ID = "369633995349-7apl7m77mpeo4231b1kl2v3nonqi60ga.apps.googleusercontent.com"
GITHUB_CLIENT_ID = "Ov23liTtfl1NQmZtq2em"
LINKEDIN_CLIENT_ID = "86fimn7a7dwvmr"

# AWS SES 邮件服务配置
AWS_REGION = "us-west-2"
FROM_EMAIL = "noreply@svtr.ai"

# 飞书API配置（开发环境）
FEISHU_APP_ID = "cli_a8e2014cbe7d9013"
FEISHU_APP_SECRET = "tysHBj6njxwafO92dwO1DdttVvqvesf0"

# Preview环境配置 (Cloudflare Pages支持的环境名称)
[env.preview]
name = "chatsvtr-preview"
compatibility_date = "2024-07-16"

[env.preview.vars]
APP_URL = "https://preview.svtr.ai"

# 定时任务配置 - 融资日报每日自动更新
# 注意：Cloudflare Pages不支持cron triggers
# 定时任务需要单独创建Worker处理
# [triggers]
# crons = [
#   # 每天北京时间09:00 (UTC+8) = UTC 01:00 执行融资数据更新
#   "0 1 * * *"
# ]

# Secrets 通过wrangler secret命令设置
# OAuth secrets:
# wrangler pages secret put GOOGLE_CLIENT_SECRET
# wrangler pages secret put GITHUB_CLIENT_SECRET
# wrangler pages secret put LINKEDIN_CLIENT_SECRET
# AWS SES secrets:
# wrangler pages secret put AWS_ACCESS_KEY_ID
# wrangler pages secret put AWS_SECRET_ACCESS_KEY
# Feishu API secrets:
# wrangler pages secret put FEISHU_APP_ID
# wrangler pages secret put FEISHU_APP_SECRET


