name = "chatsvtr"
compatibility_date = "2024-07-16"
pages_build_output_dir = "."

# Enable Gzip/Brotli compression for all text-based assets
[[headers]]
for = "*.css"
[headers.values]
"Content-Encoding" = "gzip"
"Cache-Control" = "public, max-age=31536000, immutable"

[[headers]]
for = "*.js"
[headers.values]
"Content-Encoding" = "gzip"
"Cache-Control" = "public, max-age=31536000, immutable"

[[headers]]
for = "*.html"
[headers.values]
"Content-Encoding" = "gzip"
"Cache-Control" = "public, max-age=3600"

[[headers]]
for = "*.webp"
[headers.values]
"Cache-Control" = "public, max-age=31536000, immutable"

[[headers]]
for = "*.png"
[headers.values]
"Cache-Control" = "public, max-age=31536000, immutable"

[[headers]]
for = "*.jpg"
[headers.values]
"Cache-Control" = "public, max-age=31536000, immutable"

# Security headers for all pages
[[headers]]
for = "/*"
[headers.values]
"Content-Security-Policy" = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://cdn.jsdelivr.net; style-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net; img-src 'self' data: https:; connect-src 'self' https:; font-src 'self' https:; object-src 'none'; base-uri 'self'; form-action 'self'"
"X-Content-Type-Options" = "nosniff"
"X-Frame-Options" = "DENY"
"X-XSS-Protection" = "1; mode=block"
"Referrer-Policy" = "strict-origin-when-cross-origin"
"Permissions-Policy" = "camera=(), microphone=(), geolocation=()"

[[vectorize]]
binding = "SVTR_VECTORIZE"
index_name = "autorag-svtr-knowledge-base-ai"

[[kv_namespaces]]
binding = "SVTR_KV"
id = "c474461b59eb4b1696492fdf037e05cf"

[ai]
binding = "AI"