#!/bin/bash

echo "🔄 强制清除浏览器缓存的解决方案"
echo "================================="
echo ""
echo "请在浏览器中执行以下操作："
echo ""
echo "方法1: 键盘快捷键"
echo "  • Windows/Linux: Ctrl + Shift + R"
echo "  • macOS: Cmd + Shift + R"
echo ""
echo "方法2: 开发者工具清除"
echo "  1. 按F12打开开发者工具"
echo "  2. 右键点击刷新按钮"
echo "  3. 选择'硬性重新加载'或'清空缓存并硬性重新加载'"
echo ""
echo "方法3: 手动清除缓存"
echo "  1. 在地址栏输入 chrome://settings/content/all"
echo "  2. 搜索localhost:3000"
echo "  3. 删除相关存储数据"
echo ""
echo "方法4: 添加缓存破坏参数"
echo "  访问: http://localhost:3000?v=$(date +%s)"
echo ""
echo "当前时间戳: $(date +%s)"
echo "完整URL: http://localhost:3000?v=$(date +%s)"
echo ""
echo "✅ 缓存清除后，应该看到真实AI API调用，而非演示模式"