# Cloudflare Pages 配置文件
name = "chatsvtr"
compatibility_date = "2024-07-16"
pages_build_output_dir = "."

# Cloudflare Workers AI 配置
[ai]
binding = "AI"

# 静态资源缓存
[[headers]]
for = "/assets/*"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "*.html"
[headers.values]
Cache-Control = "public, max-age=0, must-revalidate"

# 重定向规则
[[redirects]]
from = "/AI 100.html"
to = "/pages/ai-100.html"
status = 301

[[redirects]]
from = "/凯瑞.jpg"
to = "/assets/images/qr-code.jpg"
status = 301

# SPA fallback
[[redirects]]
from = "/*"
to = "/index.html"
status = 200