name: Fast CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  # 快速检查 - 只运行必要的检查，45秒内完成
  quick-check:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci --prefer-offline --no-audit
    
    # 并行运行快速检查
    - name: Run quick checks
      run: |
        # 并行运行linting和HTML验证
        npm run lint &
        npm run validate:html &
        wait
    
    - name: Run unit tests
      run: npm test
    
    - name: Basic smoke test
      run: |
        # 快速检查核心文件是否存在
        test -f index.html || exit 1
        test -f assets/js/main.js || exit 1
        test -f assets/css/style.css || exit 1
        echo "✅ Basic smoke test passed"

  # 完整测试 - 只在main分支或手动触发时运行
  full-test:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch'
    timeout-minutes: 5
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Install Playwright browsers
      run: npx playwright install --with-deps chromium
    
    - name: Run E2E tests
      run: npm run test:e2e
    
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: test-results
        path: |
          test-results/
          playwright-report/
        retention-days: 7

  # 自动部署 - 只在测试通过后运行
  auto-deploy:
    runs-on: ubuntu-latest
    needs: quick-check
    if: github.ref == 'refs/heads/main'
    timeout-minutes: 2
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Deploy to Cloudflare Pages
      run: |
        echo "✅ Auto-deployment would run here"
        echo "Skipping actual deployment - add Cloudflare CLI commands when ready"